### ISSUE TITLE
database implementation

### ISSUE THREAD

**Issue by gMakunde** [msu-sp20-cosc458/project-3-Bear-Bites#1]

**Comment by kthompson1102** [comment]
Created code that took the menu from dining.json and put it into the database .

**Comment by kthompson1102** [comment]
in postgreSQL , I had to ALTER TABLE to make column lengths long enough to accept the strings from the file

**Comment by kthompson1102** [comment]
**************** menu.py code to insert menu items to database*****************************
import json
import models
import dining


f = open('dining.json')
menu = json.load(f)
for menu_item in menu:
    food_item = models.menuItem(menu_item['title'],0, menu_item['calories'],None, menu_item['types'],"Rawling's Dining Hall", menu_item['image'])
    models.db.session.add(food_item)
    models.db.session.commit()
f.close()
