### ISSUE TITLE
impementation of twilio api to email users the menu every morning when they sign up

### ISSUE THREAD

**Issue by gMakunde** [msu-sp20-cosc458/project-3-Bear-Bites#14]

**Comment by Norbeen** [comment]
Working on this next.

**Comment by Norbeen** [comment]
Installation process for the required library in twillio.

https://www.twilio.com/docs/libraries/python

**Comment by Norbeen** [comment]
We could deploy the code to heroku and add environment variable in heroku and see if that works 

or, we need to create an environment variable in terminal and check it but mine shows error. I am doing hit and trial.

Code: 
# using SendGrid's Python Library
# https://github.com/sendgrid/sendgrid-python
import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

message = Mail(
    from_email='from_email@example.com',
    to_emails='to@example.com',
    subject='Sending with Twilio SendGrid is Fun',
    html_content='<strong>and easy to do anywhere, even with Python</strong>')
try:
    sg = SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
    response = sg.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
except Exception as e:
    print(e.message)


Link for api is here: 

https://app.sendgrid.com/guide/integrate/langs/python

**Comment by Norbeen** [comment]
Used python script because twilio wasn't working/ was giving hard time implementation.
