### ISSUE TITLE
module not found error in testing

### ISSUE THREAD

**Issue by Norbeen** [msu-sp20-cosc458/project-3-Bear-Bites#28]

**Comment by gMakunde** [comment]
can you give a little more context? what module was not found, copy and paste the whole error message. Which files in testing did it effect? and what have you tried so far

**Comment by gMakunde** [comment]
also what version of python is it? try using the python3 command instead of python

**Comment by Norbeen** [comment]
It seems like aws was having some issue bc I might have installed some library doing some process. I will create a new environment and work on that.
