### ISSUE TITLE
steamed broccoli photo cannot be fetched

### ISSUE THREAD

**Issue by gMakunde** [msu-sp20-cosc458/project-3-Bear-Bites#30]
![Screen Shot 2020-04-19 at 3 43 16 PM](https://user-images.githubusercontent.com/34068912/79698127-c5771180-8254-11ea-8065-a58c5d37da99.png)
![Screen Shot 2020-04-19 at 3 43 31 PM](https://user-images.githubusercontent.com/34068912/79698128-c6a83e80-8254-11ea-9e9a-4df55312d8f1.png)

**Comment by gMakunde** [comment]
we probably need to replace this photo with an adequate one

**Comment by ketim1** [comment]
#closed
