### ISSUE TITLE
google login

### ISSUE THREAD

**Issue by gMakunde** [msu-sp20-cosc458/project-3-Bear-Bites#9]

**Comment by Norbeen** [comment]
Issues: 
The issue I had while trying to run the app.py was that, when I tried to render the react components, it wouldn't show the UI at all. 

How I resolved: 
In order, to solve that here are the commands.

- updated webpack.config.js and package.json for google signin
- added <script src="https://apis.google.com/js/platform.js" async defer></script> to index.html
- $ npm install react-google-login
- npm install 7
- npm install 
- npm install --save-dev webpack
- killall node
- rm -rf ios/build/
- react-native run-ios
- sudo apt install cmdtest
- npm install --save react-router-dom

UI showed up, now we need to add a button showing up

**Comment by ketim1** [comment]
Issues:
I had many issues while I was trying to run, like some Uncaught TypeError: Object(...) it not a function, Uncaught TypeError: Bootstrap's javascript requires, (...) it not a function, Uncaught TypeError: Cannot read property "_ reactInternalIstance$hdqcuje27nj' of null and same issue which is related with jQuery 
                   How I resolved some issues:
Finally, I solved some issues by making capital letters in the content.jsx like in (FoodCard) and some other and I also added a line to solve the jQuery problem in index.htm on line 28 "<script src="static/jquery.min.js"></script> but still the button for the Google Sign in does not show up.

**Comment by gMakunde** [comment]
The problem stemmed from using an old version of react. After updating to the current version, i was able to see the button rendered
